_target_: src.datasets.huggingface_dataset.KaggleChatbotArenaDataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
is_preprocessed: ${is_preprocessed}
data_column_names: ${data_column_names}
prompt_column_name: ${prompt_column_name}
target_column_names: ${target_column_names}
label_column_name: ${label_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
custom_data_encoder_path: ${custom_data_encoder_path}
left_padding: ${left_padding}
data_max_length: ${data_max_length}
target_max_length: ${target_max_length}