defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: kaggle-lmsys-chatbot-arena
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

voted_probability: ${connected_dir}/probabilities/${voted_name}.npy
submission_file: ${connected_dir}/data/sample_submission.csv
target_column_names:
  - winner_model_a
  - winner_model_b
  - winner_tie
voted_file: ${connected_dir}/submissions/${voted_name}.csv

votings:
  probability1: 0.5
  probability2: 0.5